### ISSUE TITLE
Link hover content with transparent background and weird font styles

### ISSUE THREAD

**Issue by compadrejunior** [pengx17/logseq-plugin-link-preview#122]
Hi folks,

When I mouse over a link the preview cards renders a the title and description with a transparent background, no borders and weird font styles. 

Here`s an example? 
![image](https://user-images.githubusercontent.com/13987735/210870656-83e53075-4531-48f9-a2d3-5befa77bd13d.png)

First time I install the plugin, it works fine. After closing and reopening Logseq the error occurs and then persists.

Thanks in advance.

Regards,

José Compadre Junior

**Comment by pengx17** [comment]
Can you try using the default theme and see if the style looks fine?

**Comment by sagiwei** [comment]
I use ` logseq-awesome-styler` plugin, but even switch to `Logseq original` theme, preview still with a transparent background like @compadrejunior 's snapshot.

**Comment by sagiwei** [comment]
> I use ` logseq-awesome-styler` plugin, but even switch to `Logseq original` theme, preview still with a transparent background like @compadrejunior 's snapshot.

Finally, I found it caused by ` logseq-awesome-styler` plugin, error occurs whenever this plugin turns on.

**Comment by yoyurec** [comment]
CSS vars missed
![image](https://user-images.githubusercontent.com/137919/224021065-0569de78-cad7-47cc-a48b-3d43c096c917.png)

looks like AwStyler loads little longer and script can't get them. What about wrap with `setTimeout` for ~1 or 2sec?
https://github.com/pengx17/logseq-plugin-link-preview/blob/master/src/App.tsx#L12-L38

**Comment by yoyurec** [comment]
fixed + improved `// FIXME: adapt for dynamic theme mode change` )

**Comment by DutchPete** [comment]
I just installed this plug-in and have the Awesome Styler also. The transparent background still occurs, so I am not sure what @yoyurec means by “fixed + improved”.

**Comment by DutchPete** [comment]
@Gitbreast thanks a lot.
